pipeline{
    agent any

    /*
        **NOTE: refresh the job page to enable the Parameters
        The "Build" on the left panel will change to "Build with Parameters"
        Build => Build with Parameters
    */
    parameters {
        booleanParam(name:'CreateResources', defaultValue:false, description: 'Apply or Destroy on efs, rds, vpc, s3, etc.')
        booleanParam(name:'DestroyResources', defaultValue:false, description: 'Select when you want to destroy resources, or else to apply')
    }
	environment {
		AWS_Cred = "aws_jr9"
		Working_Dir = "applications/helloworld-api-gateway-lambda"
	}
    
    stages{
        
        stage('Terraform init'){
            steps{
				ansiColor('vga'){
					withAWS(credentials: "$AWS_Cred", region: 'ap-southeast-1') {
						dir("$Working_Dir") {
							sh "terraform  init"
						}
					}
				}
            }
        }
        
        stage('Terraform apply'){
            when { 
                expression{ return params.CreateResources }
                expression{ return !params.DestroyResources}
            }
            steps{
				ansiColor('vga'){
					withAWS(credentials: "$AWS_Cred", region: 'ap-southeast-1') {
						dir("$Working_Dir") {
							sh "terraform  apply --auto-approve"
						}
					}
				}
            }
        }
        
        stage('Terraform destroy'){
            when { 
                expression{ return !params.CreateResources }
                expression{ return params.DestroyResources }
            }
            steps{
				ansiColor('vga'){
					withAWS(credentials: "$AWS_Cred", region: 'ap-southeast-1') {
						dir("$Working_Dir") {
							sh "terraform  destroy --auto-approve"
						}
					}
				}
            }
        }
    }

	post {
		always {
			//clean workspace
			cleanWs()
		}
	}	
}